spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: book-service
            uri: lb://book-service
            predicates:
              - Path=/v1/book/**
          - id: library-service
            uri: lb://library-service
            predicates:
              - Path=/v1/library/**
        discovery:
          loacator:
            enabled: true




server:
  port: 8889

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true


management:
  endpoint:
    web:
      exposure:
        include: "*"
        exclude: info


zipkin:
  base-url: http://localhost:9411